import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
const supabase=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),$=id=>document.getElementById(id)
const BRL=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),NUM=v=>(Number(v)||0).toLocaleString('pt-BR')
let state={rows:[],balances:[],payments:[],params:null,view:'resumo',charts:[]}
async function fetchAllSalesItems(){let all=[],from=0,size=1000;while(true){const {data,error}=await supabase.from('sales_items').select('*').order('sale_date',{ascending:false}).range(from,from+size-1);if(error)throw error;all=all.concat(data||[]);if((data||[]).length<size)break;from+=size}return all}
async function loadAll(){try{$('content').textContent='Carregando dados...';const [rows,params,balances,payments]=await Promise.all([fetchAllSalesItems(),supabase.from('pricing_params').select('*').eq('active',true).limit(1),supabase.from('v_repayment_balance').select('*').order('period_key',{ascending:false}),supabase.from('payments').select('*').order('paid_at',{ascending:false}).limit(500)]);state.rows=rows;state.params=(params.data||[])[0]||null;state.balances=balances.data||[];state.payments=payments.data||[];fillFilters();render()}catch(e){$('content').textContent=e.message||String(e)}}
function filters(){return{month:$('monthFilter').value,company:$('companyFilter').value,channel:$('channelFilter').value}}
function rows(){const f=filters();return state.rows.filter(r=>(!f.month||r.month===f.month)&&(!f.company||r.company===f.company)&&(!f.channel||r.channel===f.channel))}
function balances(){const f=filters();return state.balances.filter(r=>(!f.month||r.period_key===f.month)&&(!f.company||r.company===f.company))}
function fillFilters(){const fill=(id,vals,txt)=>{const cur=$(id).value;$(id).innerHTML=`<option value="">${txt}</option>`+[...new Set(vals)].sort().map(v=>`<option>${v}</option>`).join('');$(id).value=cur};fill('monthFilter',state.rows.map(r=>r.month),'Todos os meses');fill('companyFilter',state.rows.map(r=>r.company),'Todas empresas');fill('channelFilter',state.rows.map(r=>r.channel),'Todos canais')}
function sum(rs){const orders=new Set(rs.map(r=>r.marketplace_order_id));return{fat:rs.reduce((a,r)=>a+Number(r.gross_value||0),0),rep:rs.reduce((a,r)=>a+Number(r.transfer_total_value||0),0),orders:orders.size,itens:rs.reduce((a,r)=>a+Number(r.quantity||0),0),missing:rs.filter(r=>!r.cost_found).length}}
function cards(rs){const s=sum(rs),bal=balances().reduce((a,r)=>a+Number(r.balance_company||0),0);$('cards').innerHTML=[['Faturamento',BRL(s.fat),''],['Repasse',BRL(s.rep),''],['Saldo devedor',BRL(bal),'bad'],['Pedidos',NUM(s.orders),''],['Alertas custo',NUM(costAlerts(rs).length),'warn']].map(c=>`<div class="card"><div class="label">${c[0]}</div><div class="value ${c[2]}">${c[1]}</div></div>`).join('')}
function groupBy(rs,key,val='transfer_total_value'){const m={};rs.forEach(r=>{m[r[key]||'—']=(m[r[key]||'—']||0)+Number(r[val]||0)});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function destroyCharts(){state.charts.forEach(c=>c.destroy());state.charts=[]}
function chart(id,type,labels,data,label,color){const c=new Chart($(id),{type,data:{labels,datasets:[{label,data,borderColor:color,backgroundColor:color+'55',tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});state.charts.push(c)}
function table(rs){return`<div style="overflow:auto"><table><thead><tr><th>Data</th><th>Empresa</th><th>Canal</th><th>Pedido</th><th>SKU</th><th class="num">Venda</th><th class="num">Repasse</th><th>Custo</th></tr></thead><tbody>${rs.slice(0,1200).map(r=>`<tr><td>${r.sale_date||''}</td><td>${r.company}</td><td>${r.channel}</td><td>${r.marketplace_order_id||''}</td><td>${r.sku}</td><td class="num">${BRL(r.gross_value)}</td><td class="num">${BRL(r.transfer_total_value)}</td><td>${r.cost_found?'ok':'<span class="warn">sem custo</span>'}</td></tr>`).join('')}</tbody></table></div>`}
function unitSale(r){return Number(r.gross_unit_value||(Number(r.gross_value||0)/Number(r.quantity||1))||0)}
function costAlerts(rs){return rs.map(r=>{const vendaUnit=unitSale(r),custo=Number(r.cost_unit||0),costPct=vendaUnit>0&&r.cost_found&&custo>0?custo/vendaUnit:null,alerts=[];let severity=0;if(costPct!==null&&costPct>=.80){alerts.push('Custo consome 80% ou mais da venda unitária');severity=3}else if(costPct!==null&&costPct>=.60){alerts.push('Custo consome acima de 60% da venda unitária');severity=2}return{...r,vendaUnit,costPct,alerts,severity}}).filter(r=>r.alerts.length).sort((a,b)=>b.severity-a.severity||Number(b.gross_value||0)-Number(a.gross_value||0))}
function renderAlertas(rs){const a=costAlerts(rs);$('content').innerHTML=`<h2>Alertas de custo</h2><p>SKUs sem custo ficam na aba própria. Aqui aparecem apenas produtos cujo custo parece alto demais: acima de 60% do valor vendido unitário.</p><table><thead><tr><th>Sev.</th><th>Empresa</th><th>SKU</th><th>Descrição</th><th class="num">Venda unit.</th><th class="num">Custo</th><th class="num">Custo/Venda</th><th>Motivo</th></tr></thead><tbody>${a.slice(0,1500).map(r=>`<tr><td>${r.severity>=3?'<span class="bad">Crítico</span>':'<span class="warn">Atenção</span>'}</td><td>${r.company}</td><td>${r.sku}</td><td>${r.description||''}</td><td class="num">${BRL(r.vendaUnit)}</td><td class="num">${BRL(r.cost_unit)}</td><td class="num">${r.costPct===null?'—':(r.costPct*100).toFixed(1)+'%'}</td><td>${r.alerts.join('; ')}</td></tr>`).join('')}</tbody></table>`}
function renderResumo(rs){const months=groupBy(rs,'month','transfer_total_value').sort();$('content').innerHTML=`<div class="grid"><div class="panel"><h2>Repasse por mês</h2><div class="chartbox"><canvas id="chart1"></canvas></div></div><div class="panel"><h2>Ranking empresas</h2>${summaryTable(groupBy(rs,'company','transfer_total_value'))}</div></div>`;chart('chart1','line',months.map(x=>x[0]),months.map(x=>x[1]),'Repasse','#017efa')}
function summaryTable(arr){return`<table><thead><tr><th>Nome</th><th class="num">Valor</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${x[0]}</td><td class="num">${BRL(x[1])}</td></tr>`).join('')}</tbody></table>`}
function renderAlertas(rs){const a=costAlerts(rs);$('content').innerHTML=`<h2>Alertas de custo</h2><p>Regra: custo ausente/zerado, custo menor que 5% ou 10% da venda unitária, custo menor que R$1 em venda acima de R$20, ou repasse unitário menor que 20%/30% da venda unitária.</p><table><thead><tr><th>Sev.</th><th>Empresa</th><th>SKU</th><th>Descrição</th><th class="num">Venda unit.</th><th class="num">Custo</th><th class="num">Custo/Venda</th><th>Motivo</th></tr></thead><tbody>${a.slice(0,1500).map(r=>`<tr><td>${r.severity>=3?'<span class="bad">Crítico</span>':'<span class="warn">Atenção</span>'}</td><td>${r.company}</td><td>${r.sku}</td><td>${r.description||''}</td><td class="num">${BRL(r.vendaUnit)}</td><td class="num">${r.cost_found?BRL(r.cost_unit):'—'}</td><td class="num">${r.costPct===null?'—':(r.costPct*100).toFixed(1)+'%'}</td><td>${r.alerts.join('; ')}</td></tr>`).join('')}</tbody></table>`}
function renderSaldos(){const b=balances();$('content').innerHTML=`<h2>Saldos de repasse</h2><table><thead><tr><th>Mês</th><th>Empresa</th><th class="num">Repasse devido</th><th class="num">Pago</th><th class="num">Saldo</th><th>Status</th></tr></thead><tbody>${b.map(r=>`<tr><td>${r.period_key}</td><td>${r.company}</td><td class="num">${BRL(r.amount_due)}</td><td class="num">${BRL(r.amount_paid_company)}</td><td class="num">${BRL(r.balance_company)}</td><td>${r.status}</td></tr>`).join('')}</tbody></table><p class="warn">Lançamento de pagamento bloqueado; esta tela é consulta.</p>`}
function renderParams(){const p=state.params||{};$('content').innerHTML=`<h2>Parâmetros</h2><div class="cards"><div class="card"><div class="label">Imposto</div><div class="value">${p.tax_percent||14}%</div></div><div class="card"><div class="label">Operacional eq.</div><div class="value">${p.operational_percent||44}%</div></div><div class="card"><div class="label">Margem</div><div class="value">${p.margin_percent||5}%</div></div><div class="card"><div class="label">Líquido</div><div class="value">${p.net_percent||37}%</div></div></div>`}
function render(){destroyCharts();const rs=rows();cards(rs);if(state.view==='resumo')renderResumo(rs);if(state.view==='faturamento')$('content').innerHTML=table(rs.sort((a,b)=>Number(b.gross_value)-Number(a.gross_value)));if(state.view==='repasse')$('content').innerHTML=table(rs.sort((a,b)=>Number(b.transfer_total_value)-Number(a.transfer_total_value)));if(state.view==='saldos')renderSaldos();if(state.view==='alertas')renderAlertas(rs);if(state.view==='skus')$('content').innerHTML=table(rs.filter(r=>!r.cost_found));if(state.view==='parametros')renderParams();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
async function login(){const {data,error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}enter(data.session)}
function enter(session){$('login').classList.add('hidden');$('app').classList.remove('hidden');$('userBox').innerHTML=`<button id="logoutBtn">Sair</button>`;$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};loadAll()}
$('loginBtn').onclick=login;$('refreshBtn').onclick=loadAll;['monthFilter','companyFilter','channelFilter'].forEach(id=>$(id).onchange=render);document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});supabase.auth.getSession().then(({data})=>{if(data.session)enter(data.session)})
