import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
const supabase=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),$=id=>document.getElementById(id)
const BRL=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),NUM=v=>(Number(v)||0).toLocaleString('pt-BR')
let state={rows:[],balances:[],payments:[],params:null,view:'resumo',charts:[]}
const views=[['resumo','Dashboard'],['faturamento','Faturamento'],['repasse','Repasse'],['saldos','Saldos'],['alertas','Alertas de custo'],['skus','SKUs sem custo'],['parametros','Parâmetros']]
async function fetchAllSalesItems(){let all=[],from=0,size=1000;while(true){const {data,error}=await supabase.from('sales_items').select('*').order('sale_date',{ascending:false}).range(from,from+size-1);if(error)throw error;all=all.concat(data||[]);if((data||[]).length<size)break;from+=size}return all}
async function loadAll(){try{$('content').textContent='Carregando dados atualizados...';const [rows,params,balances,payments]=await Promise.all([fetchAllSalesItems(),supabase.from('pricing_params').select('*').eq('active',true).limit(1),supabase.from('v_repayment_balance').select('*').order('period_key',{ascending:false}),supabase.from('payments').select('*').order('paid_at',{ascending:false}).limit(500)]);state.rows=rows;state.params=(params.data||[])[0]||null;state.balances=balances.data||[];state.payments=payments.data||[];fillFilters();render()}catch(e){$('content').textContent=e.message||String(e)}}
function filters(){return{month:$('monthFilter').value,company:$('companyFilter').value,channel:$('channelFilter').value}}
function rows(){const f=filters();return state.rows.filter(r=>(!f.month||r.month===f.month)&&(!f.company||r.company===f.company)&&(!f.channel||r.channel===f.channel))}
function bals(){const f=filters();return state.balances.filter(r=>(!f.month||r.period_key===f.month)&&(!f.company||r.company===f.company))}
function fillFilters(){const fill=(id,vals,txt)=>{const cur=$(id).value;$(id).innerHTML=`<option value="">${txt}</option>`+[...new Set(vals)].sort().map(v=>`<option>${v}</option>`).join('');$(id).value=cur};fill('monthFilter',state.rows.map(r=>r.month),'Todos os meses');fill('companyFilter',state.rows.map(r=>r.company),'Todas empresas');fill('channelFilter',state.rows.map(r=>r.channel),'Todos canais')}
function sum(rs){const orders=new Set(rs.map(r=>r.marketplace_order_id));return{fat:rs.reduce((a,r)=>a+Number(r.gross_value||0),0),rep:rs.reduce((a,r)=>a+Number(r.transfer_total_value||0),0),orders:orders.size,itens:rs.reduce((a,r)=>a+Number(r.quantity||0),0),missing:rs.filter(r=>!r.cost_found).length}}
function unitSale(r){return Number(r.gross_unit_value||(Number(r.gross_value||0)/Number(r.quantity||1))||0)}
function costAlerts(rs){return rs.map(r=>{const vendaUnit=unitSale(r),custo=Number(r.cost_unit||0),costPct=vendaUnit>0&&r.cost_found&&custo>0?custo/vendaUnit:null,alerts=[];let severity=0;if(costPct!==null&&costPct>=.80){alerts.push('Custo consome 80% ou mais da venda unitária');severity=3}else if(costPct!==null&&costPct>=.60){alerts.push('Custo consome acima de 60% da venda unitária');severity=2}return{...r,vendaUnit,costPct,alerts,severity}}).filter(r=>r.alerts.length).sort((a,b)=>b.severity-a.severity||Number(b.gross_value||0)-Number(a.gross_value||0))}
function cards(rs){const s=sum(rs),bal=bals().reduce((a,r)=>a+Number(r.balance_company||0),0),alerts=costAlerts(rs).length;const data=[['Faturamento',BRL(s.fat),'text-slate-900'],['Repasse',BRL(s.rep),'text-indigo-600'],['Saldo devedor',BRL(bal),'text-rose-600'],['Pedidos',NUM(s.orders),'text-slate-900'],['Alertas custo',NUM(alerts),'text-amber-600']];$('cards').innerHTML=data.map(x=>`<div class="card-kpi"><div class="text-sm text-slate-500">${x[0]}</div><div class="mt-2 text-2xl font-black ${x[2]}">${x[1]}</div></div>`).join('')}
function groupBy(rs,key,val='transfer_total_value'){const m={};rs.forEach(r=>{m[r[key]||'—']=(m[r[key]||'—']||0)+Number(r[val]||0)});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function destroyCharts(){state.charts.forEach(c=>c.destroy());state.charts=[]}
function makeChart(id,type,labels,data,label,color){const c=new Chart($(id),{type,data:{labels,datasets:[{label,data,borderColor:color,backgroundColor:color+'44',tension:.35,borderWidth:3,fill:type==='line'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{ticks:{callback:v=>BRL(v)}}}});state.charts.push(c)}
function table(rs){return`<div class="table-wrap"><table class="w-full text-sm"><thead><tr><th>Data</th><th>Empresa</th><th>Canal</th><th>Pedido</th><th>SKU</th><th class="num">Qtd</th><th class="num">Venda</th><th class="num">Repasse</th><th>Custo</th></tr></thead><tbody>${rs.slice(0,1500).map(r=>`<tr><td>${r.sale_date||''}</td><td>${r.company}</td><td>${r.channel}</td><td>${r.marketplace_order_id||''}</td><td>${r.sku}</td><td class="num">${NUM(r.quantity)}</td><td class="num">${BRL(r.gross_value)}</td><td class="num">${BRL(r.transfer_total_value)}</td><td>${r.cost_found?'<span class="ok">ok</span>':'<span class="warn">sem custo</span>'}</td></tr>`).join('')}</tbody></table></div>`}
function summaryTable(arr){return`<div class="table-wrap"><table class="w-full text-sm"><thead><tr><th>Nome</th><th class="num">Valor</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${x[0]}</td><td class="num font-semibold">${BRL(x[1])}</td></tr>`).join('')}</tbody></table></div>`}
function renderResumo(rs){const monthRep=groupBy(rs,'month','transfer_total_value').sort(),monthFat=groupBy(rs,'month','gross_value').sort();$('content').innerHTML=`<div class="grid grid-cols-1 xl:grid-cols-3 gap-5"><div class="xl:col-span-2"><h2 class="text-xl font-bold mb-4">Evolução mensal</h2><div class="chartbox"><canvas id="chart1"></canvas></div></div><div><h2 class="text-xl font-bold mb-4">Ranking empresas</h2>${summaryTable(groupBy(rs,'company','transfer_total_value'))}</div></div>`;makeChart('chart1','line',monthRep.map(x=>x[0]),monthRep.map(x=>x[1]),'Repasse','#6366f1')}
function renderSaldos(){const b=bals();$('content').innerHTML=`<h2 class="text-xl font-bold mb-4">Saldos de repasse</h2><div class="table-wrap"><table class="w-full text-sm"><thead><tr><th>Mês</th><th>Empresa</th><th class="num">Repasse devido</th><th class="num">Pago</th><th class="num">Saldo</th><th>Status</th></tr></thead><tbody>${b.map(r=>`<tr><td>${r.period_key}</td><td>${r.company}</td><td class="num">${BRL(r.amount_due)}</td><td class="num">${BRL(r.amount_paid_company)}</td><td class="num font-bold">${BRL(r.balance_company)}</td><td>${r.status}</td></tr>`).join('')}</tbody></table></div><p class="mt-4 text-amber-600 text-sm">Lançamento de pagamento bloqueado; consulta apenas.</p>`}
function renderAlertas(rs){const a=costAlerts(rs);$('content').innerHTML=`<h2 class="text-xl font-bold mb-2">Alertas de custo</h2><p class="text-sm text-slate-500 mb-4">SKUs sem custo ficam em aba própria. Aqui aparecem custos acima de 60% da venda unitária.</p><div class="table-wrap"><table class="w-full text-sm"><thead><tr><th>Sev.</th><th>Empresa</th><th>SKU</th><th>Descrição</th><th class="num">Venda unit.</th><th class="num">Custo</th><th class="num">Custo/Venda</th><th>Motivo</th></tr></thead><tbody>${a.slice(0,1500).map(r=>`<tr><td>${r.severity>=3?'<span class="bad font-semibold">Crítico</span>':'<span class="warn font-semibold">Atenção</span>'}</td><td>${r.company}</td><td>${r.sku}</td><td>${r.description||''}</td><td class="num">${BRL(r.vendaUnit)}</td><td class="num">${BRL(r.cost_unit)}</td><td class="num">${(r.costPct*100).toFixed(1)}%</td><td>${r.alerts.join('; ')}</td></tr>`).join('')}</tbody></table></div>`}
function renderParams(){const p=state.params||{};$('content').innerHTML=`<h2 class="text-xl font-bold mb-4">Parâmetros de cálculo</h2><div class="grid grid-cols-1 sm:grid-cols-4 gap-4">${[['Imposto',p.tax_percent||14],['Operacional eq.',p.operational_percent||44],['Margem',p.margin_percent||5],['Percentual líquido',p.net_percent||37]].map(x=>`<div class="card-kpi"><div class="text-sm text-slate-500">${x[0]}</div><div class="mt-2 text-3xl font-black text-slate-900">${x[1]}%</div></div>`).join('')}</div>`}
function render(){destroyCharts();const rs=rows();cards(rs);if(state.view==='resumo')renderResumo(rs);if(state.view==='faturamento')$('content').innerHTML=`<h2 class="text-xl font-bold mb-4">Faturamento</h2>`+table([...rs].sort((a,b)=>Number(b.gross_value)-Number(a.gross_value)));if(state.view==='repasse')$('content').innerHTML=`<h2 class="text-xl font-bold mb-4">Repasse</h2>`+table([...rs].sort((a,b)=>Number(b.transfer_total_value)-Number(a.transfer_total_value)));if(state.view==='saldos')renderSaldos();if(state.view==='alertas')renderAlertas(rs);if(state.view==='skus')$('content').innerHTML=`<h2 class="text-xl font-bold mb-4">SKUs sem custo</h2>`+table(rs.filter(r=>!r.cost_found));if(state.view==='parametros')renderParams();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
async function login(){const {data,error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}enter(data.session)}
function enter(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('userBox').innerHTML='<button id="logoutBtn" class="rounded-xl bg-slate-900 text-white px-4 py-2 font-semibold">Sair</button>';$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};loadAll()}
function initNav(){const mob=$('mobileNav');mob.innerHTML=views.map(([v,t])=>`<button data-view="${v}" class="nav bg-slate-900 text-white">${t}</button>`).join('');document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()})}
$('loginBtn').onclick=login;$('refreshBtn').onclick=loadAll;['monthFilter','companyFilter','channelFilter'].forEach(id=>$(id).onchange=render);initNav();supabase.auth.getSession().then(({data})=>{if(data.session)enter()})
